name: Setup Nix + Devenv
description: Checkout repo, install Nix, configure Cachix, and install devenv
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
    - name: Configure Cachix
      uses: cachix/cachix-action@v16
      with:
        name: devenv
    - name: Install devenv.sh
      shell: bash
      run: nix profile install nixpkgs#devenv
